spring:
  cloud:
    gateway:
      routes:
        - id: cervejas
          uri: lb://CERVEJA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/cerveja/**
        - id: pedidos
          uri: lb://PEDIDO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/pedido/**
        - id: fabricantes
          uri: lb://FABRICANTE-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/fabricante/**

  application:
    name: gateway-service
server:
  port: 9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://EUREKA-SERVER:8761/eureka