spring:
  application:
    name: imposto-service
app:
  myport: 8080
server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://EUREKA-SERVER:8761/eureka